## @file testminimax.py
#  @title testminmax
#  @author Jenny Feng Chen
#  @date 04/07/2016

def main():
    #format for input of initial state(example): X, ,O, , , ,O, ,X
    print("Example of input state: ' ,O,X, , ,O, , ,X'")
    S=input("Enter the initial State of the board seperated by comma: ")
    player=input("Player: ")
    TreeBuild(S.split(','),player)
    
def TreeBuild(S,player):
#takes initial S and player initial
#returns a list of all game states generated by the game tree with root S
     return helper(S,player,True)

def helper(S,player,isMax):
    l=[]
    for i in range(len(S)):
        l.append(S[i])
    #change the opponent value when the turn changes
    if player=='X':
        oppo='O'
    else:
        oppo='X'
    #first checking the base case whether it is a winning state for X
    if checkWinState(S,player)==True:
        if isMax==True:
            l.append(1)
            l.append(player)
            l.append((-1,-1))
            #print the state and value
            getString(str(l[:9]),l)
            return l
        else:
            l.append(-1)
            l.append(player)
            l.append((-1,-1))
            getString(str(l[:9]),l)
            return l
    #checking the base case whether it is a winning state for O
    if checkWinState(S,oppo)==True:
        if isMax==True:
            l.append(-1)
            l.append(player)
            l.append((-1,-1))
            getString(str(l[:9]),l)
            return l
        else:
            l.append(1)
            l.append(player)
            l.append((-1,-1))
            getString(str(l[:9]),l)
            return l
    isFull=True
    #check whether there is space in the state
    for i in range(len(S)):
        if S[i]==' ':
            isFull=False
            break
    #if no space then return value 0 which means draw
    if isFull==True:
         l.append(0)
         l.append(player)
         l.append((-1,-1))
         getString(str(l[:9]),l)
         return l
    count=[]
    #find the space in the state and take the index of each of the space into a list
    for i in range(len(S)):
        if S[i]==' ':
            count.append(i)
    value=[]
    #put the player to the space and call the function to determine the value of state
    for i in range(len(count)):
        S[count[i]]=player
        L=helper(S,oppo,not isMax)
        value.append(L[9])
        S[count[i]]=' '
    #take the maximum value or minimum value for the current player and determine the position
    if isMax==True:
        val=max(value)
        pos=value.index(max(value))
    else:
        val=min(value)
        pos=value.index(min(value))
    #convert to the coordinate system
    move=(count[pos]//3,count[pos]%3)
    l.append(val)
    l.append(player)
    l.append(move)
    #print the state and value
    getString(str(l[:9]),l)
    return l

#function for checking the winning state
def checkWinState(S, player):
    return ((S[6] == player and S[7] == player and S[8] == player) or # across the top
            (S[3] == player and S[4] == player and S[5] == player) or # across the middle
            (S[0] == player and S[1] == player and S[2] == player) or # across the bottom
            (S[6] == player and S[3] == player and S[0] == player) or # down the left side
            (S[7] == player and S[4] == player and S[1] == player) or # down the middle
            (S[8] == player and S[5] == player and S[2] == player) or # down the right side
            (S[6] == player and S[4] == player and S[2] == player) or # diagonal
            (S[8] == player and S[4] == player and S[0] == player)) # diagonal

#make the printing format to be as same as the project displayed
def getString(string,l):
    newS='';i=0
    while i < len(string):
        n=string[i]
        if string[i]==',':
            if string[i+1]==" ":
                newS+=string[i]
                i+=1
        elif string[i]!="'":
            newS+=string[i]
        i+=1
    print('State='+newS+', '+'Value='+str(l[9]))
